SRC_DIR := $(dir $(lastword $(MAKEFILE_LIST)))

EXTRA_INCL += -I$(SRC_DIR)

#EXTRA_CLEAN +=

include Makefile.sub

all: $(A)test_levelorderlookup

$(A)test_levelorderlookup: $(O)test_levelorderlookup.o
	$(LINK)

