SRC_DIR := $(dir $(lastword $(MAKEFILE_LIST)))

EXTRA_INCL += -I$(SRC_DIR)

MY_TARGETS = $(A)test_pair $(A)test_list $(A)test_stl $(A)test_idgenerator $(A)test_file

#$(A)test_duallist

EXTRA_CLEAN += $(MY_TARGETS)

include Makefile.sub

all: $(MY_TARGETS)


PAIR_OBJ = $(O)pair.o $(O)pairblob.o $(O)nmea0183checksumcalculator.o $(O)mytime.o
DISKTABLE_OBJ = $(O)disktable.o $(O)mmapfile.o $(O)diskfileheader.o


$(A)test_pair: $(O)test_pair.o $(PAIR_OBJ)
	$(LINK)

$(A)test_list: $(O)test_list.o $(O)stlvectorlist.o $(O)vectorlist.o $(O)linklist.o $(O)skiplist.o $(PAIR_OBJ) $(O)djbhash.o
	$(LINK)

$(A)test_stl: $(O)test_stl.o $(PAIR_OBJ)
	$(LINK)

$(A)test_idgenerator: $(O)test_idgenerator.o $(O)idgeneratorts.o $(O)idgeneratordate.o $(O)mytime.o
	$(LINK)

$(A)test_file: $(O)test_file.o $(O)stlvectorlist.o $(O)vectorlist.o $(O)linklist.o $(O)skiplist.o $(PAIR_OBJ) $(DISKTABLE_OBJ) $(O)djbhash.o
	$(LINK)

#$(A)test_duallist: $(O)test_duallist.o $(O)skiplist.o $(PAIR_OBJ) $(DISKTABLE_OBJ)
#	$(LINK)

